name: generate-image-wall

on:
  schedule:
    - cron: '0 17* * *' #01:00 UTC+8 everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.0'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script to generate movie poster wall
        run: python image_wall.py -i=66888874 -c=18 -r=8 -o=8 -rd=True

#      - name: execute py script to generate album cover wall
#        run: python image_wall.py -i=49729399 -m='music' -c=10 -r=8 -o=8 -rd=True -s=True
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update poster wall image." -a

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
